# dataset
data_source: 'd_conf_input'
# select from:
# 1) ISPdataset:
# it loads the stored dataset
# 2) random_uniform:
# it generates a random default vector where each element has probability of being 1 equal to default_prob
# 3) random_incr:
# it generates a random default vector where the i-th (zero-based) element has probability of being 1 equal to i/n
# 4) random_num_def:
# it generates a default vector having d = 1 default_module times
# 5) d_screen_input:
# it requires the default vector as a screen input
# 6) d_conf_input:
# it requires the one_indices, i. e. the config parameter having the indices of the default vector with value equal to 1
# 7) real_dist:
# it generates a random default vector with a probability of having d = 1 increasing w. r. t. the index of counterparts

n_counterpart: 12
grades: 3

default_prob: 0.1                   # valid only if data_source: 'random_uniform'
                                    # default_prob is the probability of default (range: 0 - 1) per counterpart
default_module: 1                   # valid only if data_source: 'random_num_def' (range: 1 - n-2)
                                    # default_module is the number of counterparts in default
one_indices: [9,11]                  
                                    # valid only if data_source: 'd_conf_input'
                                    # one_indices is the list of the 0-based indices (range: 0 - n-1)
                                    # having default equal to 1

data_path: 'data/dataset-ispq.csv'  # ISP dataset, if absent, it returns an error
attributes:                         # select optional attributes from ISP dataset
    years: [2012, 2015]             # list of (not consecutive) years from 2012 to 2020, [] = ignore attribute
    sector: 'no'
    revenue: 'no'
    geo_area: 'no'

# solvers
solvers:
    brute_force: False
    dwave_exact: False
    annealing: False
    gurobi: True

alpha_concentration: 0.05           # range: 0 - 1, threshold of the adjust Herf index
alpha_heterogeneity: 0.01           # range: 0 - 1, threshold of the gaussian probability
alpha_homogeneity: 0.05             # range: 0 - 1, threshold of the gaussian probability

# QUBO constraints to include
constraints:
    one_class: True
    logic: True
    monotonicity: True
    concentration: True
    min_thr: True
    max_thr: True

# QUBO coefficients
mu: 
    one_class: 50
    logic:
        first_last_class: 10
        subm_1000: 10
        subm_0001: 10
        subm_0110: 10
        restart: 10
        column_one: 10
        change_class: 10
    monotonicity: 2
    concentration: 5
    min_thr: 2
    max_thr: 2

# constraints to check for each solution
test:
    logic: True
    monotonicity: True
    heterogeneity: True
    concentration: True
    min_thr: True
    max_thr: True
    homogeneity: True

# annealer parameters
shots: 100000
reads: 10

# gurobi parameters
gurobi_n_sol: 10
gurobi_fidelity: 1